all: swap os.Rename with robustio.Rename
To attempt to resolve a Windows test flake in how we write logins.json,
use robustio.Rename consistently, which retries on Windows in case
a file is concurrently read or written.
We don't hold the lock file when doing reads, so that case is possible.

    --- FAIL: TestConcurrentTokenRefresh (0.67s)
        quicktest.go:12:
            error:
              got non-nil value
            got:
              e`module foo.mod09@v0.0.1: cannot do HTTP request: [...]\001\config\logins.json: Access is denied.`
            stack:
              D:/a/cue-trybot/cue-trybot/mod/modconfig/modconfig_test.go:282
                qt.Assert(t, qt.IsNil(err))

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: Idd00c12ecc945967eddc06643d08d63d06dcf36b