Update patch set 3
Change has been successfully cherry-picked as f9c8d98d1c31cbf34e376eb3eb78984b24476136

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: internal/mod/modfile/modfile_test.go
Insertions: 2, Deletions: 2.

@@ -73,8 +73,8 @@
 module: "foo.com/bar@v0"
 `,
 	wantError: `langugage: field not allowed:
-    cuelang.org/go/internal/mod/modfile/schema.cue:14:8
-    cuelang.org/go/internal/mod/modfile/schema.cue:16:2
+    cuelang.org/go/internal/mod/modfile/schema.cue:28:8
+    cuelang.org/go/internal/mod/modfile/schema.cue:30:2
     module.cue:2:1`,
 }, {
 	testName: "InvalidLanguageVersion",
```


Patch-set: 3
Subject: internal/mod/modfile: add copyright message
Status: merged
Commit: f9c8d98d1c31cbf34e376eb3eb78984b24476136
Tag: autogenerated:gerrit:merged
Groups: 3a951e6ee7f3aac47d3d98f4a29c1ed702b103e7
Label: Code-Review=+2, 0749818fb3c48591275050cd94fef15ce01ebd00
Label: Unity-Result=+1, b1a672e825ae6f985c2c7322c873f2fa19e6576c Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 90437e1f9f97007c97a8faeb7be3ef0fc9cfca4d Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, a072258d705d2a2411d9d531b5ad4308c6db9b89
Submission-id: 1171838
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}