update to cockroachdb/apd v3
The main breaking change that apd/v3 brings is that it no longer uses
math/big types directly. There are new wrapper types which avoid
allocations in many common cases. See the added calls to MathBigInt and
SetMathBigInt.

The other breaking change happened in Quo and Sqrt,
causing the operations in CUE to end up with different precision:

	=== RUN   TestMarshalJSON
	=== RUN   TestMarshalJSON/22/a:_1.0/1
		types_test.go:2758:
			 got {"a":1.00000000000000000000000};
			want {"a":1.0}
	--- FAIL: TestMarshalJSON (0.00s)
		--- FAIL: TestMarshalJSON/22/a:_1.0/1 (0.00s)

Get the old behavior back by overwriting the Quo and Sqrt methods,
running a short piece of code to do what v2 used to do.
This makes the unit tests pass again.

As a small bonus, whenever we use Quo or Rem on an apd float,
the resulting Decimal is now consistently reduced,
leaving at least one digit after the decimal point.

For example, cue/testdata/resolve/006_arithmetic.txtar worked out
"4.0 / 2.0" as "2", but now it is "2.0".
Similarly, cue/testdata/basicrewrite/002_arithmetic.txtar worked out
"1.0T / 2.0" as "5.0000000000E+11", but now it is "5.0E+11".

To properly change the behavior of Quo and Rem across the codebase,
internal.BaseContext is now of type internal.Context,
which embeds apd.Context. internal.BaseContext is now used everywhere,
except for cue/literal, as that would result in cyclic imports.
For now that is fine, since that package uses neither Quo nor Rem.

If we want cue/literal to use the same custom apd.Context as the rest of
the codebase, we could always move internal.Context to avoid the cycle.

Fixes #1872.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: Iadcb4a50f7c9943601a1124570387f62ed65a6f5