cmd/cue/cmd: replace TestScriptDebug with an env var
While looking over the tests, I noticed TestScriptDebug, added back in
early 2020 to allow debugging CUE running as part of a testscript.
This makes sense, since testscript would otherwise run cue commands as
separate processes, which is normally what we want for integration tests.

However, TestScriptDebug went through quite a bit of trouble to
reimplement testscript: parsing txtar files, extracting files, parsing
commands, finding the first cue command, and running it directly.

We have an easier and better way to do that: instead of setting up cue
as a RunMain command, which then runs as a separate process,
we set it up as part of Params.Cmds, which run in the same process.

This is less code than the previous approach, as we don't reimplement
testscript. Moreover, it will support more complex scripts, as any
commands before the first cue command will run normally. We also drop
the dependency on shlex, which is a nice plus, especially given that
testscript command syntax is not the same as shell syntax.

We keep this feature behind an env var, so that the regular TestScript
behaves the same way it used to:

	$ go test -run TestScript/^eval_e$
	PASS
	ok  	cuelang.org/go/cmd/cue/cmd	0.081s
	$ TESTSCRIPT_SAME_PROCESS=true go test -run TestScript/^eval_e$
	--- FAIL: TestScript (0.02s)
		--- FAIL: TestScript/eval_e (0.02s)
			testscript.go:397:
				> ! cue eval -e nonExist
				FAIL: testdata/script/eval_e.txt:1: terminating because of errors: reference "nonExist" not found:
					--expression:1:1
	FAIL
	exit status 1
	FAIL	cuelang.org/go/cmd/cue/cmd	0.039s

While here, move the inTest docs next to where inTest is set.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: I643b6e9bbab6255f620418db2b51f17fdd981481