Update patch set 56
Change has been successfully cherry-picked as d5c0745eb65196ff1739d1ab5bf5af455c7d2422

51 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: cmd/cue/cmd/testdata/script/registry_with_pkg.txtar
Insertions: 38, Deletions: 0.

@@ -0,0 +1,38 @@
+# When CUE_REGISTRY is correctly set, packages in the
+# pkg directory are ignored.
+exec cue export .
+cmp stdout expect-stdout
+
+-- expect-stdout --
+"registry source"
+-- main.cue --
+package main
+import "example.com/e"
+
+e.foo
+
+-- cue.mod/module.cue --
+module: "test.org"
+deps: "example.com/e": v: "v0.0.1"
+
+-- cue.mod/pkg/example.com/e/cue.mod/module.cue --
+module: "example.com/e"
+
+-- cue.mod/pkg/example.com/e/main.cue --
+package e
+foo: "cue.mod/pkg source"
+
+-- cue.mod/pkg/example.com/e/cue.mod/module.cue --
+module: "example.com/e"
+
+-- cue.mod/pkg/example.com/e/main.cue --
+package e
+foo: "cue.mod/pkg source"
+
+-- _registry/example.com_e_v0.0.1/cue.mod/module.cue --
+module: "example.com/e@v0"
+
+-- _registry/example.com_e_v0.0.1/main.cue --
+package e
+
+foo: "registry source"
```
```
The name of the file: cmd/cue/cmd/testdata/script/registry_experiment_not_set.txtar
Insertions: 3, Deletions: 3.

@@ -6,7 +6,7 @@
 cmp stdout expect-stdout
 
 -- expect-stdout --
-"ok"
+"cue.mod/pkg source"
 -- main.cue --
 package main
 import "example.com/e"
@@ -21,7 +21,7 @@
 module: "example.com/e"
 -- cue.mod/pkg/example.com/e/main.cue --
 package e
-foo: "ok"
+foo: "cue.mod/pkg source"
 
 -- _registry/example.com_e_v0.0.1/cue.mod/module.cue --
 module: "example.com/e@v0"
@@ -29,4 +29,4 @@
 -- _registry/example.com_e_v0.0.1/main.cue --
 package e
 
-foo: "not ok"
+foo: "registry source"
```
```
The name of the file: go.mod
Insertions: 1, Deletions: 1.

@@ -3,7 +3,7 @@
 go 1.20
 
 require (
-	cuelabs.dev/go/oci/ociregistry v0.0.0-20230928144906-bef4f4e03886
+	cuelabs.dev/go/oci/ociregistry v0.0.0-20231004130125-2c3ad8a6ecd3
 	github.com/cockroachdb/apd/v3 v3.2.1
 	github.com/emicklei/proto v1.10.0
 	github.com/go-quicktest/qt v1.101.0
```
```
The name of the file: internal/mod/modregistry/client.go
Insertions: 1, Deletions: 1.

@@ -65,7 +65,7 @@
 	modDesc, err := c.registry.ResolveTag(ctx, repoName, m.Version())
 	if err != nil {
 		if errors.Is(err, ociregistry.ErrManifestUnknown) {
-			return nil, fmt.Errorf("module %q: %w", m, ErrNotFound)
+			return nil, fmt.Errorf("module %v: %w", m, ErrNotFound)
 		}
 		return nil, fmt.Errorf("module %v: %v", m, err)
 	}
```
```
The name of the file: cmd/cue/cmd/registry.go
Insertions: 11, Deletions: 4.

@@ -15,14 +15,18 @@
 )
 
 func getRegistry() (ociregistry.Interface, error) {
-	if !cueexperiment.Flags.Modules {
-		return nil, nil
-	}
 	// TODO document CUE_REGISTRY via a new "cue help environment" subcommand.
 	env := os.Getenv("CUE_REGISTRY")
+	if !cueexperiment.Flags.Modules {
+		if env != "" {
+			fmt.Fprintf(os.Stderr, "warning: ignoring CUE_REGISTRY because modules experiment is not enabled. Set CUE_EXPERIMENT=modules to enable it.\n")
+		}
+		return nil, nil
+	}
 	if env == "" {
 		env = "registry.cuelabs.dev"
 	}
+
 	host, prefix, insecure, err := parseRegistry(env)
 	if err != nil {
 		return nil, err
@@ -50,6 +54,9 @@
 		// OCI references don't allow a host name on its own without a repo,
 		// but we do.
 		r.Host = env
+		if !ociref.IsValidHost(r.Host) {
+			return "", "", false, fmt.Errorf("$CUE_REGISTRY %q is not a valid host name", r.Host)
+		}
 	} else {
 		var err error
 		r, err = ociref.Parse(env)
@@ -57,7 +64,7 @@
 			return "", "", false, fmt.Errorf("cannot parse $CUE_REGISTRY: %v", err)
 		}
 		if r.Tag != "" || r.Digest != "" {
-			return "", "", false, fmt.Errorf("$CUE_REGISTRY cannot have associated tag or digest")
+			return "", "", false, fmt.Errorf("$CUE_REGISTRY %q cannot have an associated tag or digest", env)
 		}
 	}
 	if suffix == "" {
```
```
The name of the file: cmd/cue/cmd/testdata/script/registry_wrong_prefix.txtar
Insertions: 1, Deletions: 1.

@@ -3,7 +3,7 @@
 cmp stderr expect-stderr
 
 -- expect-stderr --
-instance: example.com/e@v0.0.1: module example.com/e@v0.0.1: error response: 404 Not Found: repository name not known to registry
+instance: cannot resolve dependencies: example.com/e@v0.0.1: module example.com/e@v0.0.1: error response: 404 Not Found: repository name not known to registry
 -- main.cue --
 package main
 import "example.com/e"
```
```
The name of the file: cmd/cue/cmd/registry_test.go
Insertions: 6, Deletions: 3.

@@ -47,16 +47,19 @@
 	wantInsecure: true,
 }, {
 	registry:  "foo.com/bar:1324",
-	wantError: `\$CUE_REGISTRY cannot have associated tag or digest`,
+	wantError: `\$CUE_REGISTRY "foo.com/bar:1324" cannot have an associated tag or digest`,
 }, {
 	registry:  "foo.com/bar@sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
-	wantError: `\$CUE_REGISTRY cannot have associated tag or digest`,
+	wantError: `\$CUE_REGISTRY "foo.com/bar@sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae" cannot have an associated tag or digest`,
 }, {
 	registry:  "foo.com/bar:blah@sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae",
-	wantError: `\$CUE_REGISTRY cannot have associated tag or digest`,
+	wantError: `\$CUE_REGISTRY "foo.com/bar:blah@sha256:2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae" cannot have an associated tag or digest`,
 }, {
 	registry:  "foo.com/bar+baz",
 	wantError: `unknown suffix \("\+baz"\) to CUE_REGISTRY \(need \+insecure or \+secure\)`,
+}, {
+	registry:  "badhost",
+	wantError: `\$CUE_REGISTRY "badhost" is not a valid host name`,
 }}
 
 func TestParseRegistry(t *testing.T) {
```
```
The name of the file: cmd/cue/cmd/testdata/script/registry_no_experiment_warning.txtar
Insertions: 14, Deletions: 0.

@@ -0,0 +1,14 @@
+env CUE_EXPERIMENT=
+env CUE_REGISTRY=ignored.example.com
+exec cue export .
+cmp stdout expect-stdout
+cmp stderr expect-stderr
+
+-- expect-stdout --
+"ok"
+-- expect-stderr --
+warning: ignoring CUE_REGISTRY because modules experiment is not enabled. Set CUE_EXPERIMENT=modules to enable it.
+-- main.cue --
+package main
+
+"ok"
```
```
The name of the file: go.sum
Insertions: 2, Deletions: 3.

@@ -1,5 +1,7 @@
 cuelabs.dev/go/oci/ociregistry v0.0.0-20230928144906-bef4f4e03886 h1:v4I5Vu5DMkQXGaKAYun/2eFWQZ3Yg8IB3CSxyBee5ww=
 cuelabs.dev/go/oci/ociregistry v0.0.0-20230928144906-bef4f4e03886/go.mod h1:oqwWmDcccWVB2yC2eCHFNrQR44/AVB7gHOwtBsWMo0g=
+cuelabs.dev/go/oci/ociregistry v0.0.0-20231004130125-2c3ad8a6ecd3 h1:jJJsm3hgxosEoI5wXrwt8mv21j23vInE3owbSYKhR2c=
+cuelabs.dev/go/oci/ociregistry v0.0.0-20231004130125-2c3ad8a6ecd3/go.mod h1:oqwWmDcccWVB2yC2eCHFNrQR44/AVB7gHOwtBsWMo0g=
 github.com/cockroachdb/apd/v3 v3.2.1 h1:U+8j7t0axsIgvQUqthuNm82HIrYXodOV2iWLWtEaIwg=
 github.com/cockroachdb/apd/v3 v3.2.1/go.mod h1:klXJcjp+FffLTHlhIG69tezTDvdP065naDsHzKhYSqc=
 github.com/cpuguy83/go-md2man/v2 v2.0.2/go.mod h1:tgQtvFlXSQOSOSIRvRPT7W67SCa46tRHOmNcaadrF8o=
@@ -21,9 +23,7 @@
 github.com/kr/text v0.2.0 h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=
 github.com/kr/text v0.2.0/go.mod h1:eLer722TekiGuMkidMxC/pM04lWEeraHUUmBw8l2grE=
 github.com/kylelemons/godebug v1.1.0 h1:RPNrshWIDI6G2gRW9EHilWtl7Z6Sb1BR0xunSBf0SNc=
-github.com/kylelemons/godebug v1.1.0/go.mod h1:9/0rRGxNHcop5bhtWyNeEfOS8JIWk580+fNqagV/RAw=
 github.com/lib/pq v1.10.7 h1:p7ZhMD+KsSRozJr34udlUrhboJwWAgCg34+/ZZNvZZw=
-github.com/lib/pq v1.10.7/go.mod h1:AlVN5x4E4T544tWzH6hKfbfQvm3HdbOxrmggDNAPY9o=
 github.com/mitchellh/go-wordwrap v1.0.1 h1:TLuKupo69TCn6TQSyGxwI1EblZZEsQ0vMlAFQflz0v0=
 github.com/mitchellh/go-wordwrap v1.0.1/go.mod h1:R62XHJLzvMFRBbcrT7m7WgmE1eOyTSsCt+hzestvNj0=
 github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de h1:D5x39vF5KCwKQaw+OC9ZPiLVHXz3UFw2+psEX+gYcto=
@@ -50,7 +50,6 @@
 golang.org/x/net v0.15.0 h1:ugBLEUaxABaB5AJqW9enI0ACdci2RUd4eP51NTBvuJ8=
 golang.org/x/net v0.15.0/go.mod h1:idbUs1IY1+zTqbi8yxTbhexhEEk5ur9LInksu6HrEpk=
 golang.org/x/sync v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
-golang.org/x/sync v0.3.0/go.mod h1:FU7BRWz2tNW+3quACPkgCx/L+uEAv1htQ0V83Z9Rj+Y=
 golang.org/x/sys v0.12.0 h1:CM0HF96J0hcLAwsHPJZjfdNzs0gftsLfgKt57wWHJ0o=
 golang.org/x/sys v0.12.0/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
 golang.org/x/text v0.13.0 h1:ablQoSUd0tRdKxZewP80B+BaqeKJuVhuRxj/dkrun3k=
```
```
The name of the file: cue/load/instances.go
Insertions: 1, Deletions: 1.

@@ -63,7 +63,7 @@
 		}
 		deps1, err := resolveDependencies(c.modFile, regClient)
 		if err != nil {
-			return []*build.Instance{c.newErrInstance(err)}
+			return []*build.Instance{c.newErrInstance(fmt.Errorf("cannot resolve dependencies: %v", err))}
 		}
 		deps = deps1
 
```
```
The name of the file: cmd/cue/cmd/testdata/script/registry_invalid_env.txtar
Insertions: 1, Deletions: 1.

@@ -4,7 +4,7 @@
 cmp stderr expect-stderr
 
 -- expect-stderr --
-cannot make OCI client: invalid host "malformed!registry@url" (does not correctly form a host part of a URL)
+$CUE_REGISTRY "malformed!registry@url" is not a valid host name
 -- main.cue --
 package main
 import "example.com/e"
```
```
The name of the file: cue/load/testdata/testfetch/depnotfound.txtar
Insertions: 1, Deletions: 1.

@@ -1,5 +1,5 @@
 -- out/modfetch/error --
-instance: example.com@v0.0.1: module example.com@v0.0.1: error response: 404 Not Found: repository name not known to registry
+instance: cannot resolve dependencies: example.com@v0.0.1: module example.com@v0.0.1: error response: 404 Not Found: repository name not known to registry
 -- cue.mod/module.cue --
 module: "main.org@v0"
 
```
```
The name of the file: cmd/cue/cmd/testdata/script/registry_module_not_found.txtar
Insertions: 4, Deletions: 1.

@@ -1,8 +1,11 @@
 ! exec cue eval .
+# TODO this error message could use improvement:
+# - the "error response: 404 Not Found: " part is redundant
+# - the module path is also repeated redundantly.
 cmp stderr expect-stderr
 
 -- expect-stderr --
-instance: example.com/e@v0.0.2: module example.com/e@v0.0.2: error response: 404 Not Found: repository name not known to registry
+instance: cannot resolve dependencies: example.com/e@v0.0.2: module example.com/e@v0.0.2: error response: 404 Not Found: repository name not known to registry
 -- main.cue --
 package main
 import "example.com/e"
```


Patch-set: 56
Subject: cmd/cue/cmd: support CUE_REGISTRY
Status: merged
Commit: d5c0745eb65196ff1739d1ab5bf5af455c7d2422
Tag: autogenerated:gerrit:merged
Groups: 48bc682e6c36d3a0427b6151aa96786792188d73
Label: Code-Review=+2, a31e7068df6bc9cc3a90cb5b337d42392eac891d Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Unity-Result=+1, 303a93d899d0ca320c9207ca4e0582205353a61c Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 27db2afaea450ca51c9db363eda5203976a990bf Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, fc5e7b55384b8c4127c78684068cb40af26f1cc1
Submission-id: 1168510
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1013536 \u003c1013536@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}