internal/mod/mvs: discard copied par tests
internal/par is copied from Go's cmd/go/internal/par,
and upstream already tests on multiple platforms with their CI,
so it's of little use for us to include and run these tests too.

Moreover, one of them seems to flake for us on Go 1.20 on windows:

    $ go test ./...
    [...]
    --- FAIL: TestWorkParallel (1.02s)
        work_test.go:53: par.Work.Do does not seem to be parallel
    FAIL
    FAIL	cuelang.org/go/internal/mod/mvs/internal/par	1.647s

It's unclear if it is something we should look into further,
but the par code and tests certainly work on the latest version of Go
on a recent Windows per upstream's CI, so that's enough for now.

Fixes #2683.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: I33fac288313554355cf358b3419b96cedf23f56c
Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/1172066
Unity-Result: CUE porcuepine <cue.porcuepine@gmail.com>
TryBot-Result: CUEcueckoo <cueckoo@cuelang.org>
Reviewed-by: Roger Peppe <rogpeppe@gmail.com>