Update patch set 8
Change has been successfully cherry-picked as 8d043e786c78ce95cad493e2e09ec6dda5e1cb5b

5 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: mod/modfile/modfile_test.go
Insertions: 5, Deletions: 5.

@@ -104,7 +104,7 @@
 	data: `
 language: version: "v0.4.3"
 module: "foo.com/bar@v0"
-source: kind: "none"
+source: kind: "self"
 `,
 	want: &File{
 		Language: &Language{
@@ -112,7 +112,7 @@
 		},
 		Module: "foo.com/bar@v0",
 		Source: &Source{
-			Kind: "none",
+			Kind: "self",
 		},
 	},
 	wantDefaults: map[string]string{
@@ -129,11 +129,11 @@
 	wantError: `source.kind: 2 errors in empty disjunction:
 source.kind: conflicting values "git" and "bad":
     cuelang.org/go/mod/modfile/schema.cue:45:11
-    cuelang.org/go/mod/modfile/schema.cue:167:18
+    cuelang.org/go/mod/modfile/schema.cue:166:18
     module.cue:4:15
-source.kind: conflicting values "none" and "bad":
+source.kind: conflicting values "self" and "bad":
     cuelang.org/go/mod/modfile/schema.cue:45:11
-    cuelang.org/go/mod/modfile/schema.cue:167:9
+    cuelang.org/go/mod/modfile/schema.cue:166:9
     module.cue:4:15`,
 }, {
 	testName: "AmbiguousDefaults",
```
```
The name of the file: mod/modfile/schema.cue
Insertions: 4, Deletions: 5.

@@ -160,12 +160,11 @@
 #Source: {
 	// kind specifies the kind of source.
 	//
-	// The special value "none" signifies that
-	// the module that is standalone,
-	// associated with no particular source other than
+	// The special value "none" signifies that the module that is
+	// standalone, associated with no particular source other than
 	// the contents of the module itself.
-	kind!: "none" | "git"
+	kind!: "self" | "git"
 
 	// TODO support for other VCSs:
-	// kind!: "none" | "git" | "bzr" | "hg" | "svn"
+	// kind!: "self" | "git" | "bzr" | "hg" | "svn"
 }
```


Patch-set: 8
Subject: mod/modfile: add support for "source" field
Status: merged
Commit: 8d043e786c78ce95cad493e2e09ec6dda5e1cb5b
Tag: autogenerated:gerrit:merged
Groups: 6684029f81f6e697910c510e79d8927af20e9883
Label: Code-Review=+2, 3a54a948a15ee9506811e5486049fb6cec98c3fd Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Unity-Result=+1, 172dbb735bcd335807d348be784eb7c4106892f7 Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 804a46c13e770f34efb7cd6cbd3e49c95ecdf0ed Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, 71df72f95cb50a2f34fedd883f12f36fb949be5e
Submission-id: 1192905
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1013536 \u003c1013536@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017720 \u003c1017720@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}