mod/modconfig: swap os.ReadFile and os.Rename with robustio
On windows it is forbidden to read a file if it is concurrently replaced
or to rename a file if it is concurrently read.
ReadLogins using os.ReadFile and UpdateRegistryConfig using os.Rename
could conflict with one another on Windows, since only the latter
grabs the file lock to avoid losing information when ran concurrently.

The alternative would be to also hold the file lock on reads,
but that has two disadvantages:

First, it would lower concurrency on all platforms, even though this
sort of bug is only present on Windows. Punishing Windows users in the
rare case of a filesystem race seems better than punishing all users
by adding locking to every file read, which will happen often.

Second, there may be other processes reading or writing logins.json,
such as the sort of antivirus software that many Windows machines run.
It seems best to be defensive with robustio and not make assumptions.

Should solve the following two flakes, when reading and when renaming:

    --- FAIL: TestConcurrentTokenRefresh (0.55s)
       quicktest.go:12:
           error:
             got non-nil value
           got:
             e`module foo.mod13@v0.0.1: cannot do HTTP request: [...]\001\config\logins.json: The process cannot access the file because it is being used by another process.`

    --- FAIL: TestConcurrentTokenRefresh (0.67s)
        quicktest.go:12:
            error:
              got non-nil value
            got:
              e`module foo.mod09@v0.0.1: cannot do HTTP request: [...]\001\config\logins.json: Access is denied.`

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: Idd00c12ecc945967eddc06643d08d63d06dcf36b
Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/1188431
Reviewed-by: Roger Peppe <rogpeppe@gmail.com>
TryBot-Result: CUEcueckoo <cueckoo@gmail.com>