tools/flow: prevent a nil pointer panic due to internal/core/dep.empty
internal/core/dep makes use of "empty" vertices in some cases,
which have a nil BaseValue field.
One such vertex was making its way to tools/flow
after https://cuelang.org/cl/556460 was submitted to master,
via the chain of Parent vertices.

We can't easily add a check against "empty" when internal/core/dep
calls out to tools/flow, like https://cuelang.org/cl/533475 did,
since the "empty" vertex is somewhere in the chain of parents.
A general fix in internal/core/dep could be considered in the future,
given that here we only fix one of the visitors, tools/flow.

The added test reproduced the panic without the fix:

    --- FAIL: TestFlow (0.01s)
        --- FAIL: TestFlow/issue2490 (0.00s)
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]

Fixes #2490.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: If1b92078ea404c24dfc36e90293f45573f577c4c