internal/ci: fix goreleaser in non-snapshot mode again
https://cuelang.org/cl/546931 changed the goreleaser CUE command to use
a list instead of a string for the exec.Run arguments.
That is a good change, as it makes the list of arguments more explicit,
but we introduced a regression where not wanting to use the --snapshot
flag meant that we ended up with an empty argument:

	error: unknown command "" for "goreleaser release"

To avoid that problem, use an if comprehension inside the list.
For debugging in the future, print the entire list of arguments too.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: If81984a15c26b797a90616554df8f7f647473afd