Update patch set 7
Change has been successfully cherry-picked as 3ad86636b3176c6cefb1ab6917453a60a58cad54

4 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: cue/testdata/builtins/error.txtar
Insertions: 59, Deletions: 46.

@@ -18,28 +18,31 @@
 
 	substituteFail: a.b + 1 | a.notExist | error("reference failed: \(a.b) | \(a.notExist)")
 }
+indirect: {
+	x: error
+	y: x("msg")
+}
 -- out/eval/stats --
 Leaks:  0
-Freed:  27
-Reused: 22
+Freed:  30
+Reused: 25
 Allocs: 5
 Retain: 0
 
-Unifications: 13
-Conjuncts:    35
-Disjuncts:    27
+Unifications: 16
+Conjuncts:    38
+Disjuncts:    30
 -- out/evalalpha --
 Errors:
 selection.twoUserErrors: 2 errors in empty disjunction:
-selection.useUserError: "use me":
+selection.useUserError: use me:
     ./in.cue:4:22
-    ./in.cue:4:28
-selection.twoUserErrors: "error one":
+selection.twoUserErrors: error one:
     ./in.cue:6:23
-    ./in.cue:6:29
-selection.twoUserErrors: "error two":
+selection.twoUserErrors: error two:
     ./in.cue:6:44
-    ./in.cue:6:50
+indirect.y: msg:
+    ./in.cue:22:5
 
 Result:
 (_|_){
@@ -48,24 +51,20 @@
     // [user]
     dropError: (int){ 1 }
     useUserError: (_|_){
-      // [user] selection.useUserError: "use me":
+      // [user] selection.useUserError: use me:
       //     ./in.cue:4:22
-      //     ./in.cue:4:28
     }
     twoUserErrors: (_|_){
       // [user] selection.twoUserErrors: 2 errors in empty disjunction:
-      // selection.twoUserErrors: "error one":
+      // selection.twoUserErrors: error one:
       //     ./in.cue:6:23
-      //     ./in.cue:6:29
-      // selection.twoUserErrors: "error two":
+      // selection.twoUserErrors: error two:
       //     ./in.cue:6:44
-      //     ./in.cue:6:50
     }
     x: (int){ int }
     dropIncomplete: (_|_){
-      // [incomplete] selection.dropIncomplete: "user msg: x + 1 failed":
+      // [incomplete] selection.dropIncomplete: user msg: x + 1 failed:
       //     ./in.cue:9:26
-      //     ./in.cue:9:32
     }
   }
   interpolation: (struct){
@@ -84,6 +83,14 @@
       //     ./in.cue:18:77
     }
   }
+  indirect: (_|_){
+    // [user]
+    x: (string){ error() }
+    y: (_|_){
+      // [user] indirect.y: msg:
+      //     ./in.cue:22:5
+    }
+  }
 }
 -- diff/-out/evalalpha<==>+out/eval --
 diff old new
@@ -100,10 +107,10 @@
 -    ./in.cue:4:16
 -    ./in.cue:4:18
 +selection.twoUserErrors: 2 errors in empty disjunction:
- selection.useUserError: "use me":
+ selection.useUserError: use me:
      ./in.cue:4:22
-     ./in.cue:4:28
-@@ -24,19 +17,12 @@
+ selection.twoUserErrors: error one:
+@@ -23,18 +16,11 @@
      // [user]
      dropError: (int){ 1 }
      useUserError: (_|_){
@@ -111,10 +118,9 @@
 -      // selection.useUserError: conflicting values 2 and 1:
 -      //     ./in.cue:4:16
 -      //     ./in.cue:4:18
--      // selection.useUserError: "use me":
-+      // [user] selection.useUserError: "use me":
+-      // selection.useUserError: use me:
++      // [user] selection.useUserError: use me:
        //     ./in.cue:4:22
-       //     ./in.cue:4:28
      }
      twoUserErrors: (_|_){
 -      // [user] selection.twoUserErrors: 3 errors in empty disjunction:
@@ -122,10 +128,10 @@
 -      //     ./in.cue:6:17
 -      //     ./in.cue:6:19
 +      // [user] selection.twoUserErrors: 2 errors in empty disjunction:
-       // selection.twoUserErrors: "error one":
+       // selection.twoUserErrors: error one:
        //     ./in.cue:6:23
-       //     ./in.cue:6:29
-@@ -46,11 +32,7 @@
+       // selection.twoUserErrors: error two:
+@@ -42,11 +28,7 @@
      }
      x: (int){ int }
      dropIncomplete: (_|_){
@@ -133,12 +139,12 @@
 -      // selection.dropIncomplete: non-concrete value int in operand to +:
 -      //     ./in.cue:9:18
 -      //     ./in.cue:8:5
--      // selection.dropIncomplete: "user msg: x + 1 failed":
-+      // [incomplete] selection.dropIncomplete: "user msg: x + 1 failed":
+-      // selection.dropIncomplete: user msg: x + 1 failed:
++      // [incomplete] selection.dropIncomplete: user msg: x + 1 failed:
        //     ./in.cue:9:26
-       //     ./in.cue:9:32
      }
-@@ -61,20 +43,11 @@
+   }
+@@ -56,20 +38,11 @@
      }
      world: (string){ "world" }
      substituteAll: (_|_){
@@ -171,15 +177,14 @@
 selection.useUserError: conflicting values 2 and 1:
     ./in.cue:4:16
     ./in.cue:4:18
-selection.useUserError: "use me":
+selection.useUserError: use me:
     ./in.cue:4:22
-    ./in.cue:4:28
-selection.twoUserErrors: "error one":
+selection.twoUserErrors: error one:
     ./in.cue:6:23
-    ./in.cue:6:29
-selection.twoUserErrors: "error two":
+selection.twoUserErrors: error two:
     ./in.cue:6:44
-    ./in.cue:6:50
+indirect.y: msg:
+    ./in.cue:22:5
 
 Result:
 (_|_){
@@ -192,21 +197,18 @@
       // selection.useUserError: conflicting values 2 and 1:
       //     ./in.cue:4:16
       //     ./in.cue:4:18
-      // selection.useUserError: "use me":
+      // selection.useUserError: use me:
       //     ./in.cue:4:22
-      //     ./in.cue:4:28
     }
     twoUserErrors: (_|_){
       // [user] selection.twoUserErrors: 3 errors in empty disjunction:
       // selection.twoUserErrors: conflicting values 2 and 1:
       //     ./in.cue:6:17
       //     ./in.cue:6:19
-      // selection.twoUserErrors: "error one":
+      // selection.twoUserErrors: error one:
       //     ./in.cue:6:23
-      //     ./in.cue:6:29
-      // selection.twoUserErrors: "error two":
+      // selection.twoUserErrors: error two:
       //     ./in.cue:6:44
-      //     ./in.cue:6:50
     }
     x: (int){ int }
     dropIncomplete: (_|_){
@@ -214,9 +216,8 @@
       // selection.dropIncomplete: non-concrete value int in operand to +:
       //     ./in.cue:9:18
       //     ./in.cue:8:5
-      // selection.dropIncomplete: "user msg: x + 1 failed":
+      // selection.dropIncomplete: user msg: x + 1 failed:
       //     ./in.cue:9:26
-      //     ./in.cue:9:32
     }
   }
   interpolation: (struct){
@@ -244,6 +245,14 @@
       //     ./in.cue:18:77
     }
   }
+  indirect: (_|_){
+    // [user]
+    x: (string){ error() }
+    y: (_|_){
+      // [user] indirect.y: msg:
+      //     ./in.cue:22:5
+    }
+  }
 }
 -- out/compile --
 --- in.cue
@@ -263,4 +272,8 @@
     substituteAll: (〈0;a〉.notExist|error("hello \(〈0;world〉)"))
     substituteFail: ((〈0;a〉.b + 1)|〈0;a〉.notExist|error("reference failed: \(〈0;a〉.b) | \(〈0;a〉.notExist)"))
   }
+  indirect: {
+    x: error
+    y: 〈0;x〉("msg")
+  }
 }
```
```
The name of the file: internal/core/adt/call.go
Insertions: 1, Deletions: 1.

@@ -91,7 +91,7 @@
 	return c.ctx.EvaluateKeepState(x)
 }
 
-// Expr returns the nth argument expression and returned as is.
+// Expr returns the nth argument expression without evaluating it.
 func (c *CallContext) Expr(i int) Expr {
 	// If the call context represents a validator call, the argument will be
 	// offset by 1.
```
```
The name of the file: internal/core/adt/expr.go
Insertions: 3, Deletions: 0.

@@ -1806,6 +1806,9 @@
 		c.IsValidator = saved
 	}()
 
+	if x.RawFunc != nil {
+		return x.RawFunc(call)
+	}
 	return x.Func(call)
 }
 
```
```
The name of the file: internal/core/compile/builtin.go
Insertions: 1, Deletions: 1.

@@ -70,7 +70,7 @@
 			}
 			b = call.Errf(w.String(), args...)
 		default:
-			msg := call.Arg(0)
+			msg := ctx.ToString(call.Arg(0))
 			b = call.Errf("%s", msg)
 		}
 
```


Patch-set: 7
Subject: internal/core/adt: add builtin for user-defined errors
Status: merged
Commit: 3ad86636b3176c6cefb1ab6917453a60a58cad54
Tag: autogenerated:gerrit:merged
Groups: e451bd8dceb4fb3f19294f0127ec022e86e131c5
Label: Code-Review=+2, e4cd504a84163eb5831b4568723e2e926ee76bbf Gerrit User 1007275 <1007275@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Unity-Result=+1, ac13a6ef267dc2e18ae5c05bd0cd8a8e9b0d15b5 Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 410333426c2a6c539d1909010f6fda7fda68b488 Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, 7726bbaccd39d465b3694dec0af9c33c30bf185b
Submission-id: 1217235
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1007275 <1007275@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}