internal/ci: make clearing of GitHub Actions caches best-effort
Because they get automatically evicted by GitHub once we use too much
space, or they might get deleted by other users or programs,
assuming that we can list caches and delete them without fail can
result in race condition errors such as:

    Error: Cache with input key 'docker.io--tonistiigi--binfmt-latest-linux-x64' does not exist

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: I09d6044d69584bf4590cf51a407e87fdbc3264df