Update patch set 3
Change has been successfully cherry-picked as 466b83b5828a6f0498c5dc22bace97de9a046f95

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: cue/testdata/builtins/issue299.txtar
Insertions: 2, Deletions: 2.

@@ -16,7 +16,7 @@
 Disjuncts:    3
 -- out/eval --
 Errors:
-x: invalid value ["x","x"] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
+x: invalid value ["x","x"] (does not satisfy list.UniqueItems): equal value ("x") at position 0 and 1:
     ./in.cue:3:4
     ./in.cue:4:4
     ./in.cue:5:4
@@ -25,7 +25,7 @@
 (_|_){
   // [eval]
   x: (_|_){
-    // [eval] x: invalid value ["x","x"] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
+    // [eval] x: invalid value ["x","x"] (does not satisfy list.UniqueItems): equal value ("x") at position 0 and 1:
     //     ./in.cue:3:4
     //     ./in.cue:4:4
     //     ./in.cue:5:4
```
```
The name of the file: internal/core/adt/composite.go
Insertions: 1, Deletions: 1.

@@ -862,7 +862,7 @@
 }
 
 // IsFinal reports whether value v can still become more specific, when only
-// regarding regular fields.
+// considering regular fields.
 //
 // TODO: move this functionality as a method on cue.Value.
 func IsFinal(v Value) bool {
```
```
The name of the file: pkg/list/list.go
Insertions: 20, Deletions: 13.

@@ -268,7 +268,7 @@
 
 	// TODO(perf): this is an O(n^2) algorithm. We should make it O(n log n).
 	// This could be done as follows:
-	// - Create a list with some has value for each element x in a as well
+	// - Create a list with some hash value for each element x in a as well
 	//   alongside the value of x itself.
 	// - Sort the elements based on the hash value.
 	// - Compare subsequent elements to see if they are equal.
@@ -282,16 +282,14 @@
 
 outer:
 	for i, x := range a {
-		var tx types.Value
-		x.Core(&tx)
+		_, vx := value.ToInternal(x)
 
 		for j := i + 1; j < len(a); j++ {
-			var ty types.Value
-			a[j].Core(&ty)
+			_, vy := value.ToInternal(a[j])
 
-			if adt.Equal(ctx, tx.V, ty.V, adt.RegularOnly) {
+			if adt.Equal(ctx, vx, vy, adt.RegularOnly) {
 				posX, posY = i, j
-				if adt.IsFinal(ty.V) {
+				if adt.IsFinal(vy) {
 					code = adt.EvalError
 					break outer
 				}
@@ -299,13 +297,22 @@
 		}
 	}
 
-	if posX != posY {
-		return false, pkg.ValidationError{B: &adt.Bottom{
-			Code: code,
-			Err:  errors.Newf(token.NoPos, "equal values at position %d and %d", posX, posY),
-		}}
+	if posX == posY {
+		return true, nil
 	}
-	return true, nil
+
+	var err errors.Error
+	switch x := a[posX].Value(); x.Kind() {
+	case cue.BoolKind, cue.NullKind, cue.IntKind, cue.FloatKind, cue.StringKind, cue.BytesKind:
+		err = errors.Newf(token.NoPos, "equal value (%v) at position %d and %d", x, posX, posY)
+	default:
+		err = errors.Newf(token.NoPos, "equal values at position %d and %d", posX, posY)
+	}
+
+	return false, pkg.ValidationError{B: &adt.Bottom{
+		Code: code,
+		Err:  err,
+	}}
 }
 
 // Contains reports whether v is contained in a. The value must be a
```
```
The name of the file: pkg/list/testdata/unique.txtar
Insertions: 12, Deletions: 12.

@@ -54,13 +54,13 @@
 }
 -- out/list-v3 --
 Errors:
-fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
+fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 1:
     ./in.cue:3:21
     ./in.cue:48:16
 fail.ignoreOptError: invalid value [~(#a),~(#abErr)] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
     ./in.cue:3:21
     ./in.cue:52:18
-fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal values at position 0 and 2:
+fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 2:
     ./in.cue:3:21
     ./in.cue:44:8
 fail.structs: invalid value [~(#a),~(#a)] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
@@ -135,11 +135,11 @@
 	structs: [#c, #c] & list.UniqueItems()
 }
 fail: {
-	ints:    _|_ // fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal values at position 0 and 2
+	ints:    _|_ // fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 2
 	structs: _|_ // fail.structs: invalid value [~(#a),~(#a)] (does not satisfy list.UniqueItems): equal values at position 0 and 1
 
 	// Hidden values do not play a role in the comparisson.
-	ignoreHidden: _|_ // fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal values at position 0 and 1
+	ignoreHidden: _|_ // fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 1
 
 	// This can be a permanent error, as the the optional field of the second
 	// element is erroneous an cannot match.
@@ -150,13 +150,13 @@
 --- old
 +++ new
 @@ -2,10 +2,13 @@
- fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
+ fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 1:
      ./in.cue:3:21
      ./in.cue:48:16
 +fail.ignoreOptError: invalid value [~(#a),~(#abErr)] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
 +    ./in.cue:3:21
 +    ./in.cue:52:18
- fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal values at position 0 and 2:
+ fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 2:
      ./in.cue:3:21
      ./in.cue:44:8
 -fail.structs: invalid value [{a:1},{a:1}] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
@@ -190,12 +190,12 @@
 @@ -83,7 +81,7 @@
  }
  fail: {
- 	ints:    _|_ // fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal values at position 0 and 2
+ 	ints:    _|_ // fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 2
 -	structs: _|_ // fail.structs: invalid value [{a:1},{a:1}] (does not satisfy list.UniqueItems): equal values at position 0 and 1
 +	structs: _|_ // fail.structs: invalid value [~(#a),~(#a)] (does not satisfy list.UniqueItems): equal values at position 0 and 1
  
  	// Hidden values do not play a role in the comparisson.
- 	ignoreHidden: _|_ // fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal values at position 0 and 1
+ 	ignoreHidden: _|_ // fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 1
 @@ -90,10 +88,5 @@
  
  	// This can be a permanent error, as the the optional field of the second
@@ -210,10 +210,10 @@
  }
 -- out/list --
 Errors:
-fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
+fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 1:
     ./in.cue:3:21
     ./in.cue:48:16
-fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal values at position 0 and 2:
+fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 2:
     ./in.cue:3:21
     ./in.cue:44:8
 fail.structs: invalid value [{a:1},{a:1}] (does not satisfy list.UniqueItems): equal values at position 0 and 1:
@@ -293,11 +293,11 @@
 	structs: [#c, #c] & list.UniqueItems()
 }
 fail: {
-	ints:    _|_ // fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal values at position 0 and 2
+	ints:    _|_ // fail.ints: invalid value [1,2,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 2
 	structs: _|_ // fail.structs: invalid value [{a:1},{a:1}] (does not satisfy list.UniqueItems): equal values at position 0 and 1
 
 	// Hidden values do not play a role in the comparisson.
-	ignoreHidden: _|_ // fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal values at position 0 and 1
+	ignoreHidden: _|_ // fail.ignoreHidden: invalid value [1,1] (does not satisfy list.UniqueItems): equal value (1) at position 0 and 1
 
 	// This can be a permanent error, as the the optional field of the second
 	// element is erroneous an cannot match.
```


Patch-set: 3
Subject: pkg/list: handle incomplete values for UniqueItems
Status: merged
Commit: 466b83b5828a6f0498c5dc22bace97de9a046f95
Tag: autogenerated:gerrit:merged
Groups: d87b50a3d96de48eb2f3bb86d43fff9a58f375e6
Label: Code-Review=+2, bc0cb0a579271bacf312a859d99b9a6ee52ca816 Gerrit User 1007275 <1007275@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Unity-Result=+1, ffb79f3efa3cef7005eec3dd6f91d0534694a92d Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, dea40ef05930a8f1ff876fd4cc48b673d5b82cce Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, f11cd474284ec037ebe4ec5227f79f125cddcec3
Submission-id: 1204378
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1007275 <1007275@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017720 \u003c1017720@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}