Update patch set 7
Change has been successfully cherry-picked as ac248f4461117fd51810de39d33adc8694297fd3

3 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: internal/mod/modrequirements/requirements.go
Insertions: 12, Deletions: 5.

@@ -31,10 +31,16 @@
 	// rootModules is the set of root modules of the graph, sorted and capped to
 	// length. It may contain duplicates, and may contain multiple versions for a
 	// given module path. The root modules are the main module's direct requirements.
-	rootModules              []module.Version
-	maxRootVersion           map[string]string
+	rootModules    []module.Version
+	maxRootVersion map[string]string
+
+	// origDefaultMajorVersions holds the original passed to New.
 	origDefaultMajorVersions map[string]string
-	defaultMajorVersions     map[string]majorVersionDefault
+
+	// defaultMajorVersions is derived from the above information,
+	// also holding modules that have a default due to being unique
+	// in the roots.
+	defaultMajorVersions map[string]majorVersionDefault
 
 	graphOnce sync.Once // guards writes to (but not reads from) graph
 	graph     atomic.Pointer[cachedGraph]
@@ -70,8 +76,6 @@
 //
 // The caller must not modify rootModules or defaultMajorVersions after passing
 // them to NewRequirements.
-//
-// /home/rogpeppe/go/src/cmd/go/internal/modload/buildlist.go:117
 func NewRequirements(mainModulePath string, reg Registry, rootModules []module.Version, defaultMajorVersions map[string]string) *Requirements {
 	mainModuleVersion := module.MustNewVersion(mainModulePath, "")
 	// TODO add direct, so we can tell which modules are directly used by the
@@ -114,6 +118,9 @@
 		rootModules:       rs.rootModules,
 		maxRootVersion:    rs.maxRootVersion,
 	}
+	// Initialize graph and graphOnce in rs1 to mimic their state in rs.
+	// We can't copy the sync.Once, so if it's already triggered, we'll
+	// run the Once with a no-op function to get the same effect.
 	rs1.graph.Store(rs.graph.Load())
 	if rs1.GraphIsLoaded() {
 		rs1.graphOnce.Do(func() {})
```
```
The name of the file: internal/mod/modload/testdata/implied-major-version-ambiguity.txtar
Insertions: 11, Deletions: 26.

@@ -1,38 +1,23 @@
-# This test checks we can have have an import with an implied major version
-# when there's no explicit default in the module file.
+# This test checks that when there are two major versions of a module
+# with no default, we don't try to resolve to one of them, but instead
+# report an error about the ambiguity.
+
+# TODO the error currently does not mention the actual ambiguity that caused
+# the issue - that should be fixed.
 -- want --
-{
-	module: "main.org@v0"
-	deps: {
-		"example.com@v0": {
-			v:       "v0.0.1"
-			default: true
-		}
-	}
-}
+error: failed to resolve "example.com/foo": cannot find module providing package example.com/foo
 -- cue.mod/module.cue --
-{
-	module: "main.org@v0"
-	deps: {
-		"example.com@v0": {
-			v:       "v0.0.1"
-		}
-		"example.com@v1": {
-			v:       "v1.0.0"
-			default: true
-		}
-	}
-}
+module: "main.org@v0"
 -- main.cue --
 package main
 
 import (
-	"example.com@v0/foo"
-	"example.com@v1/bar"
+	"example.com/foo@v0"
+	"example.com/bar@v1"
 )
 -- other.cue --
 package main
-import "example.com/bar"
+import "example.com/foo"
 
 -- _registry/example.com_v0.0.1/cue.mod/module.cue --
 module: "example.com@v0"
```
```
The name of the file: internal/mod/modload/load_test.go
Insertions: 1, Deletions: 0.

@@ -49,6 +49,7 @@
 				fmt.Fprintln(&out, v)
 			}
 			if diff := cmp.Diff(string(want), out.String()); diff != "" {
+				t.Log("actual result:\n", out.String())
 				t.Fatalf("unexpected results (-want +got):\n%s", diff)
 			}
 		})
```
```
The name of the file: internal/mod/modload/query.go
Insertions: 1, Deletions: 1.

@@ -54,7 +54,7 @@
 // package by looking for the latest module version of all viable prefixes of pkgPath.
 // It does not return modules that are already present in the given requirements.
 // It also reports whether a default major version will be required.
-func (ld *loader) queryLatestModules(ctx context.Context, pkgPath string, rs *modrequirements.Requirements) (_vers []module.Version, _def bool, _err error) {
+func (ld *loader) queryLatestModules(ctx context.Context, pkgPath string, rs *modrequirements.Requirements) ([]module.Version, bool, error) {
 	mp, mv, hasMajor := module.SplitPathVersion(pkgPath)
 	if !hasMajor {
 		mp = pkgPath
```
```
The name of the file: internal/mod/modload/load.go
Insertions: 2, Deletions: 2.

@@ -7,9 +7,9 @@
 	"io/fs"
 	"log"
 	"path"
-	"reflect"
 	"runtime"
 
+	"cuelang.org/go/internal/maps"
 	"cuelang.org/go/internal/mod/internal/par"
 	"cuelang.org/go/internal/mod/modfile"
 	"cuelang.org/go/internal/mod/modimports"
@@ -43,7 +43,7 @@
 	modFilePath := path.Join(modRoot, "cue.mod/module.cue")
 	data, err := fs.ReadFile(fsys, modFilePath)
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("cannot read cue.mod file: %v", err)
 	}
 	mf, err := modfile.ParseNonStrict(data, modFilePath)
 	if err != nil {
@@ -110,7 +110,7 @@
 		if err != nil {
 			return nil, nil, err
 		}
-		if !reflect.DeepEqual(defaultMajorVersions, rs.DefaultMajorVersions()) {
+		if !maps.Equal(defaultMajorVersions, rs.DefaultMajorVersions()) {
 			rs = rs.WithDefaultMajorVersions(defaultMajorVersions)
 		}
 		if len(modAddedBy) == 0 {
```
```
The name of the file: cmd/cue/cmd/testdata/script/modtidy_initial.txtar
Insertions: 150, Deletions: 0.

@@ -0,0 +1,150 @@
+# Check that cue mod tidy can add dependencies by
+# querying the registry, that it doesn't upgrade existing
+# dependencies, and that it removes dependencies that
+# aren't needed any more.
+
+exec cue mod tidy
+cmp cue.mod/module.cue want-module
+
+# Check that the resulting module evaluates as expected.
+exec cue export .
+cmp stdout want-stdout
+-- want-module --
+{
+	module: "main.org@v0"
+	deps: {
+		"bar.com@v0": {
+			v: "v0.5.0"
+		}
+		"baz.org@v0": {
+			v: "v0.10.1"
+		}
+		"example.com@v0": {
+			v: "v0.0.1"
+		}
+		"foo.com/bar/hello@v0": {
+			v:       "v0.2.3"
+			default: true
+		}
+	}
+}
+-- want-stdout --
+{
+    "main": "main",
+    "foo.com/bar/hello@v0": "v0.2.3",
+    "bar.com@v0": "v0.5.0",
+    "baz.org@v0": "v0.10.1",
+    "example.com@v0": "v0.0.1"
+}
+-- cue.mod/module.cue --
+module: "main.org@v0"
+
+deps: "example.com@v0": v: "v0.0.1"
+deps: "unused.com@v0": v: "v0.2.4"
+
+-- main.cue --
+package main
+import "example.com@v0:main"
+
+main
+
+-- _registry/example.com_v0.0.1/cue.mod/module.cue --
+module: "example.com@v0"
+deps: {
+	"foo.com/bar/hello@v0": v: "v0.2.3"
+	"bar.com@v0": v: "v0.5.0"
+}
+
+-- _registry/example.com_v0.0.1/top.cue --
+package main
+
+import a "foo.com/bar/hello"
+a
+main: "main"
+"example.com@v0": "v0.0.1"
+
+-- _registry/unused.com_v0.2.4/cue.mod/module.cue --
+module: "unused.com@v0"
+
+-- _registry/example.com_v0.1.2/cue.mod/module.cue --
+module: "example.com@v0"
+
+-- _registry/example.com_v0.1.2/top.cue --
+package main
+"example.com@v0": "v0.1.2"
+
+// TODO: import without a major version should
+// the major version from the module.cue file.
+main: "main"
+"example.com@v0": "v0.0.1"
+
+-- _registry/foo.com_bar_hello_v0.2.3/cue.mod/module.cue --
+module: "foo.com/bar/hello@v0"
+deps: {
+	"bar.com@v0": v: "v0.0.2"
+	"baz.org@v0": v: "v0.10.1"
+}
+
+-- _registry/foo.com_bar_hello_v0.2.3/x.cue --
+package hello
+import (
+	a "bar.com/bar@v0"
+	b "baz.org@v0:baz"
+)
+"foo.com/bar/hello@v0": "v0.2.3"
+a
+b
+
+
+-- _registry/bar.com_v0.0.2/cue.mod/module.cue --
+module: "bar.com@v0"
+deps: "baz.org@v0": v: "v0.0.2"
+
+-- _registry/bar.com_v0.0.2/bar/x.cue --
+package bar
+import a "baz.org@v0:baz"
+"bar.com@v0": "v0.0.2"
+a
+
+
+-- _registry/bar.com_v0.5.0/cue.mod/module.cue --
+module: "bar.com@v0"
+deps: "baz.org@v0": v: "v0.5.0"
+
+-- _registry/bar.com_v0.5.0/bar/x.cue --
+package bar
+import a "baz.org@v0:baz"
+"bar.com@v0": "v0.5.0"
+a
+
+
+-- _registry/baz.org_v0.0.2/cue.mod/module.cue --
+module: "baz.org@v0"
+
+-- _registry/baz.org_v0.0.2/baz.cue --
+package baz
+"baz.org@v0": "v0.0.2"
+
+
+-- _registry/baz.org_v0.1.2/cue.mod/module.cue --
+module: "baz.org@v0"
+
+-- _registry/baz.org_v0.1.2/baz.cue --
+package baz
+"baz.org@v0": "v0.1.2"
+
+
+-- _registry/baz.org_v0.5.0/cue.mod/module.cue --
+module: "baz.org@v0"
+
+-- _registry/baz.org_v0.5.0/baz.cue --
+package baz
+"baz.org@v0": "v0.5.0"
+
+
+-- _registry/baz.org_v0.10.1/cue.mod/module.cue --
+module: "baz.org@v0"
+
+-- _registry/baz.org_v0.10.1/baz.cue --
+package baz
+"baz.org@v0": "v0.10.1"
```


Patch-set: 7
Subject: internal/mod/modload: support major version defaults
Status: merged
Commit: ac248f4461117fd51810de39d33adc8694297fd3
Tag: autogenerated:gerrit:merged
Groups: 2b61f1904728507ede2cf9f69c5158f2165c5a27
Label: Code-Review=+2, 5c49abe242cf95582c35b974fd8927c897c7f133 Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Unity-Result=+1, a664fa8dff8683bb96f35bf735feb8bfb39d314e Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 4a85f8bbb766b4e9f56a33acc3b615bee6defb32 Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, df4b66fba1c0e7c1d9ae84d98af1416c86f9bc71
Submission-id: 1173288
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}