internal/core/dep: prevent passing "empty" vertices to tools/flow
internal/core/dep makes use of "empty" vertices in some cases,
which have a nil BaseValue field.
One such vertex was making its way to tools/flow
after https://cuelang.org/cl/556460 was submitted to master,
via the chain of Parent vertices.

The reason is that the CL above caused a subtle change of behavior.
By having markTaskDependencies call Dependency.Recurse directly,
which just calls visitor.visit, its `all` and `top` fields were kept.
Whereas the old markTaskDependencies recursed into itself,
setting up an entirely new visitor via dep.Visit,
resetting those fields to their initial values.

This discrepancy in the visitor boolean options caused the new code
to recurse into more vertices, hitting some of those "empty" ones,
and then causing tools/flow to panic when encountering them.

The added test reproduced the panic without the fix:

    --- FAIL: TestFlow (0.01s)
        --- FAIL: TestFlow/issue2490 (0.00s)
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]

While here, fix a presumed typo in flow_test.go.

Fixes #2490.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: If1b92078ea404c24dfc36e90293f45573f577c4c
Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/556948
Reviewed-by: Marcel van Lohuizen <mpvl@gmail.com>
TryBot-Result: CUEcueckoo <cueckoo@cuelang.org>
Unity-Result: CUE porcuepine <cue.porcuepine@gmail.com>