Update patch set 6
Change has been successfully cherry-picked as 73b3df24ebc845d6181273e3faec577686295553

4 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: mod/modfile/modfile_test.go
Insertions: 12, Deletions: 5.

@@ -54,8 +54,8 @@
 	testName: "WithDeps",
 	parse:    Parse,
 	data: `
-language: version: "v0.8.1"
 module: "foo.com/bar@v0"
+language: version: "v0.8.1"
 deps: "example.com@v1": {
 	default: true
 	v: "v1.2.3"
@@ -86,8 +86,8 @@
 	testName: "WithSource",
 	parse:    Parse,
 	data: `
-language: version: "v0.9.0-alpha.0"
 module: "foo.com/bar@v0"
+language: version: "v0.9.0-alpha.0"
 source: kind: "git"
 `,
 	want: &File{
@@ -106,8 +106,8 @@
 	testName: "WithExplicitSource",
 	parse:    Parse,
 	data: `
-language: version: "v0.9.0-alpha.0"
 module: "foo.com/bar@v0"
+language: version: "v0.9.0-alpha.0"
 source: kind: "self"
 `,
 	want: &File{
@@ -126,8 +126,8 @@
 	testName: "WithUnknownSourceKind",
 	parse:    Parse,
 	data: `
-language: version: "v0.9.0-alpha.0"
 module: "foo.com/bar@v0"
+language: version: "v0.9.0-alpha.0"
 source: kind: "bad"
 `,
 	wantError: `source.kind: 2 errors in empty disjunction:(.|\n)+`,
@@ -135,8 +135,8 @@
 	testName: "WithEarlierVersionAndSource",
 	parse:    Parse,
 	data: `
-language: version: "v0.8.6"
 module: "foo.com/bar@v0"
+language: version: "v0.8.6"
 source: kind: "git"
 `,
 	wantError: `source: conflicting values 1 and (.|\n)+`,
@@ -172,7 +172,14 @@
 	testName: "MisspelledLanguageVersionField",
 	parse:    Parse,
 	data: `
+module: "foo.com/bar@v0"
 langugage: version: "v0.4.3"
+`,
+	wantError: `no language version declared in module.cue`,
+}, {
+	testName: "MissingLanguageVersionField",
+	parse:    Parse,
+	data: `
 module: "foo.com/bar@v0"
 `,
 	wantError: `no language version declared in module.cue`,
```
```
The name of the file: mod/modfile/schema.cue
Insertions: 12, Deletions: 13.

@@ -23,16 +23,6 @@
 // to be lost. See https://github.com/cue-lang/cue/issues/2319.
 let unimplemented = 1&2
 
-#BaseFile: {
-	// We always support language.version, as we use
-	// that to determine how to parse the file itself.
-	language?: {
-		version?: string
-		...
-	}
-	...
-}
-
 // versions holds an element for each supported version
 // of the schema. The version key specifies that
 // the schema covers all versions from then until the
@@ -41,10 +31,15 @@
 versions: [string]: {
 	// #File represents the overarching module file schema.
 	#File!: {
-		#BaseFile
+		// We always require the language version, as we use
+		// that to determine how to parse the file itself.
+		// Note that this schema is not used by [ParseLegacy]
+		// because legacy module.cue files did not support
+		// language.version field.
+		language!: version!: string
 	}
 	// #Strict can be unified with the top level schema to enforce the strict version
-	// of the schema required by the registry.
+	// of the schema required when publishing a module.
 	#Strict!: _
 }
 
@@ -62,9 +57,13 @@
 earliestClosedSchemaVersion: "v0.8.0"
 
 versions: (earliestClosedSchemaVersion): {
+	// Define this version in terms of the later versions
+	// rather than the other way around, so that
+	// the latest version is clearest.
 	versions["v0.9.0-alpha.0"]
 
-	// The source field was added in v0.9.0
+	// The source field was added in v0.9.0, so "remove"
+	// it here by marking it as unimplemented.
 	#File: source?: unimplemented
 }
 
```


Patch-set: 6
Subject: mod/modfile: parse module.cue according to language.version
Status: merged
Commit: 73b3df24ebc845d6181273e3faec577686295553
Tag: autogenerated:gerrit:merged
Groups: 6684029f81f6e697910c510e79d8927af20e9883
Label: Code-Review=+2, cab050948f06cd8ef341f37b7d00d1089a2ff576 Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Unity-Result=+1, 3c5c73f8d0c4188496248701ce93a1b5836e9cbd Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 72f4afafa3f6a848d67458d4be1d537587b137be Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, a2a72c7ecb944d680bdcd8e657652c9fccc234c3
Submission-id: 1193275
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Unity-Result: Gerrit User 1020341 <1020341@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Trigger-Unity-New
Submitted-with: MAY: Unity-New-Result
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1020341 \u003c1020341@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017720 \u003c1017720@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}