internal/ci: fix goreleaser in non-snapshot mode again
https://cuelang.org/cl/546931 changed the goreleaser CUE command to use
a list instead of a string for the exec.Run arguments.
That is a good change, as it makes the list of arguments more explicit,
but we introduced a regression where not wanting to use the --snapshot
flag meant that we ended up with an empty argument:

	error: unknown command "" for "goreleaser release"

To avoid that problem, use an if comprehension inside the list.
For debugging in the future, print the entire list of arguments too.

Signed-off-by: Daniel Martí <mvdan@mvdan.cc>
Change-Id: If81984a15c26b797a90616554df8f7f647473afd
Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/549337
Reviewed-by: Paul Jolly <paul@myitcv.io>
Unity-Result: CUEcueckoo <cueckoo@cuelang.org>
TryBot-Result: CUEcueckoo <cueckoo@cuelang.org>
(cherry picked from commit 9871d8d4dc8a91d1655cf2d08ef4e6276f8e3277)
Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/549338