pkg/path: add missing param declaration
The standard library function path.Match requires 3 parameters, but only
2 are currently declared. This causes valid usage of the function to
fail with the following error:

    too many arguments in call to path.Match (have 3, want 2):

To fix this, the missing parameter declaration is added.

Fixes #3203.

Signed-off-by: Noam Dolovich <noam.tzvi.dolovich@gmail.com>
Change-Id: I6e645293f8e589ad1834e3c33ff7bffc2abb5aed